import type { NextPage } from 'next'
import Head from 'next/head'
import { Suspense } from 'react'
import { useQuery } from 'urql'
import {
  FindAllItemsQuery,
  FindAllItemsDocument,
} from '../graphql/generated/graphql'
import { format } from 'date-fns'

const Home: NextPage = () => {
  const [result] = useQuery<FindAllItemsQuery>({
    query: FindAllItemsDocument,
  })

  const { data } = result

  // if (fetching) return <p>Loading...</p>
  // if (error) return <p>Oh no... {error?.message}</p>

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-center">GB News</h1>

      <Suspense fallback={<p>Loading...</p>}>
        <ul>
          {data?.items.map((item) => (
            <li key={item.id}>
              <p>{item.name}</p>
              <p>
                {format(new Date(item.startDate), 'yyyy年MM月dd日')}〜
                {format(new Date(item.endDate), 'yyyy年MM月dd日')}
              </p>
              <p>
                ${item.basePrice}
                <span>(USD)</span>
              </p>
            </li>
          ))}
        </ul>
      </Suspense>
    </div>
  )
}

export default Home
