import { FC, ReactNode } from 'react'
import Head from 'next/head'
import Link from 'next/link'

type Props = {
  title?: string
  children: ReactNode
}

export const Layout: FC<Props> = ({ children, title = 'Group Buy News' }) => {
  return (
    <div className="bg-gray-100 px-4">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div className="mx-auto flex min-h-screen max-w-[620px] flex-col bg-white">
        <header className="pt-4 pb-10">
          <h1 className="text-center">
            <Link href="/">
              <a>{title}</a>
            </Link>
          </h1>
        </header>

        <main>{children}</main>

        <footer className="mt-auto">
          <p className="py-6 text-center text-sm">
            ©{new Date().getFullYear()} {title}
          </p>
        </footer>
      </div>
    </div>
  )
}
