import { FC, ReactNode } from 'react'
import Head from 'next/head'
import Link from 'next/link'

type Props = {
  title?: string
  children: ReactNode
}

export const Layout: FC<Props> = ({ children, title = 'Group Buy News' }) => {
  return (
    <div className="bg-black">
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <div className="mx-auto flex min-h-screen flex-col">
        <header className="sticky top-0 z-10 mb-6 flex items-center border-b border-gray-700 bg-black px-4 pt-3 pb-2">
          <Link href="/">
            <a className="logo mr-4 text-4xl font-bold">GB</a>
          </Link>

          <nav className="mb-1 flex justify-end space-x-4">
            <Link href="/">
              <a className="font-bold">Keyboards</a>
            </Link>
            <Link href="/">
              <a className="font-bold">Keycaps</a>
            </Link>
            <Link href="/">
              <a className="font-bold">Switches</a>
            </Link>
          </nav>
        </header>

        <main>{children}</main>

        <footer className="mt-auto">
          <p className="pt-14 pb-6 text-center text-sm">
            ©{new Date().getFullYear()} {title}
          </p>
        </footer>
      </div>
    </div>
  )
}
